[tools]
amp = "latest"
ast-grep = "latest"
bun = "latest"
"cargo:https://git.nokiy.net/reonokiy/nokiy.net" = "latest"
"cargo:ouch" = "latest"
"cargo:sqlx-cli" = "latest"
"cargo:xlaude" = "latest"
claude-code = "latest"
codex = "latest"
eza = "latest"
flux2 = "latest"
fnox = "latest"
gemini = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
java = "latest"
k9s = "latest"
kconf = "latest"
kubectl = "latest"
node = "lts"
"npm:@antfu/ni" = "latest"
opencode = "latest"
"pipx:nvitop" = "latest"
"pipx:ty" = "latest"
pnpm = "latest"
prek = "latest"
python = "latest"
ripgrep = "latest"
ruff = "latest"
rust = "latest"
tokei = "latest"
typst = "latest"
uv = "latest"
zoxide = "latest"
