[tools]
amp = "latest"
"cargo:sqlx-cli" = "latest"
"cargo:xlaude" = "latest"
claude-code = "latest"
codex = "latest"
fnox = "latest"
gemini = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
java = "latest"
k9s = "latest"
kconf = "latest"
kubectl = "latest"
node = "lts"
"npm:@antfu/ni" = "latest"
"pipx:ty" = "latest"
pnpm = "latest"
python = "latest"
ruff = "latest"
rust = "latest"
uv = "latest"
